### ISSUE TITLE
Container fails to run at all!

### ISSUE THREAD

**Issue by apenney** [exakat/exakat-docker#2]
Hi,

Wanted to experiment with exakat and stumbled over the container.  I got excited but:

apenney@ip-10-1-12-188:~$ sudo docker run -v $(pwd)/projects:/usr/src/exakat/projects --rm exakat/exakat docker
./exakat.phar: 1: ./exakat.phar: cannot open ?php: No such file
./exakat.phar: 2: ./exakat.phar: Syntax error: Bad function name

apenney@ip-10-1-12-188:~$ sudo docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
exakat/exakat       latest              1b4836e081fb        8 days ago          1.077 GB

**Comment by sirio3mil** [comment]
Same for me,

  PS C:\Docker\storage\exakat> docker run -v c:/www/htdocs:/usr/src/exakat/projects
--rm exakat/exakat run
./exakat.phar: 1: ./exakat.phar: cannot open ?php: No such file
./exakat.phar: 2: ./exakat.phar: Syntax error: Bad function name

Using Docker version 1.13.0, build 49bf474 in Windows 10.

Regards

**Comment by jentzheng** [comment]
https://github.com/exakat/exakat-docker/blob/master/Dockerfile#L56
syntax is incorrect, it should be `ENTRYPOINT [ "/usr/src/exakat/exakat.sh" ]`

**Comment by exakat** [comment]
The docker file has been fixed, and is currently running at version 0.10.0.
This should be fixed by now.
