### ISSUE TITLE
Fatal error: Uncaught PharException: phar

### ISSUE THREAD

**Issue by sirio3mil** [exakat/exakat-docker#3]
2017-02-18T21:41:14.464678600Z 
Fatal error: Uncaught PharException: phar "/usr/src/exakat/exakat.phar" has a broken signature in /usr/src/exakat/exakat.phar:3
Stack trace:
#0 /usr/src/exakat/exakat.phar(3): Phar::mapPhar()
#1 {main}
  thrown in /usr/src/exakat/exakat.phar on line 3

Digest: sha256:0605a1d7620250ea9fb7ff422707c69acd283cb3aa57b061108c0f494c98f5a6
Status: Downloaded newer image for exakat/exakat:latest
Creating exakat_exakat_1

exakat/exakat                         latest              3df51a9cc28f        4 days ago          1.19 GB

Regards

**Comment by exakat** [comment]
Hi Sirio3mil : 

Are you pulling the docker from docker hub or building it yourself ? 

This looks like unfinished download of the phar.

**Comment by sirio3mil** [comment]
Using Kinematic it works, not with my docker composer file

Regards
